### ISSUE TITLE
Allow per-world configuration

### ISSUE THREAD

**Issue by Pupskuchen** [Pupskuchen/spigot-TimeControl#7]
Settings that can be applied per-world should be allowed to via the configuration file.

possible config syntax:
```yaml
defaults:
  durations:
    day: 20
    night: 5
  night-skipping:
    enabled: true
  players-sleeping-percentage:
    enabled: false
    percentage: 50

worlds:
  # use defaults
  - name: 'world'
  # override some defaults
  - name: 'world2'
    durations:
      day: 30
    night-skipping: false
```
