### ISSUE TITLE
Add optional duration configuration for sunrise/sunset

### ISSUE THREAD

**Issue by Pupskuchen** [Pupskuchen/spigot-TimeControl#8]
The configuration should allow to define separate durations for sunrise and sunset, respectively.
These could be configured either by setting a duration in minutes or (optionally) by setting whether they should be treated like day or night.

e.g.
```yaml
# slow sunset that will take 5 minutes
sunset: 5
# a slightly faster sunrise
sunrise: 3
```
or
```yaml
# sunset goes as fast as the day
sunset: 'day'
# sunrise goes as fast as the night
sunrise: 'night'
```

If these are not configured explicitly, they should be treated as part of the day and use its duration config (this is the current behaviour).
